# Generated by Django 3.2.9 on 2021-11-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('nome_empresa', models.CharField(max_length=200)),
                ('nome_server', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('url_server', models.URLField()),
            ],
        ),
    ]
