# Generated by Django 3.2.9 on 2021-11-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenBanking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='svg_link',
            field=models.CharField(default='s', max_length=200),
            preserve_default=False,
        ),
    ]
