# Generated by Django 3.2.9 on 2021-11-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenBanking', '0002_servers_svg_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='svg',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
